# Generated by Django 4.1.7 on 2023-03-15 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crane",
            name="image",
            field=models.ImageField(
                default="../static/images/default.jfif", upload_to="images/"
            ),
        ),
    ]
