# Generated by Django 4.1.7 on 2023-03-15 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_alter_crane_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crane",
            name="image",
            field=models.ImageField(default="images/test.png", upload_to="images/"),
        ),
    ]
