# Generated by Django 4.1.7 on 2023-09-26 14:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0004_alter_crane_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crane",
            name="reg_no",
            field=models.CharField(editable=False, max_length=54),
        ),
    ]
