# Generated by Django 4.1.7 on 2023-09-29 10:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0005_alter_crane_reg_no"),
    ]

    operations = [
        migrations.AddField(
            model_name="crane",
            name="purchase_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 9, 29, 10, 17, 14, 273630)
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="crane",
            name="fault_type",
            field=models.CharField(
                choices=[
                    ("Corrective", "Corrective"),
                    ("PMR", "PMR"),
                    ("Unavailable", "Unavailable"),
                    ("Not Specified", "Not Specified"),
                    ("None", "None"),
                ],
                max_length=54,
            ),
        ),
    ]
