# Generated by Django 4.1.7 on 2023-09-29 10:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0007_alter_crane_fault_type_alter_crane_remark"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crane",
            name="fault_type",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="crane",
            name="remark",
            field=models.TextField(),
        ),
    ]
