# Generated by Django 4.1.7 on 2023-09-29 11:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0008_alter_crane_fault_type_alter_crane_remark"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crane",
            name="design_capacity",
            field=models.CharField(max_length=54),
        ),
        migrations.AlterField(
            model_name="cranemodel",
            name="name",
            field=models.CharField(max_length=54),
        ),
    ]
