"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 4.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-bs&(^0emzq03&-#k6)c7ylg5=*afr+3b^=5&tnb29=9)n^wltl"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*","bny-l-1517"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "dashboard.apps.DashboardConfig",
    # "django_crontab",
    #  "django_cron",

]



# CRONTAB_EXECUTABLE= BASE_DIR / 'venv/Lib/site-packages/django_crontab/crontab.py'
# CRONTAB_DJANGO_PROJECT_NAME= BASE_DIR / 'core'
# CRONTAB_DJANGO_MANAGE_PATH= BASE_DIR / 'manage.py'
# CRONTAB_PYTHON_EXECUTABLE= BASE_DIR / 'venv/Scripts/pythonw.exe'

# CRONTAB_EXECUTABLE='C:/Users/Ahmedrufai.Otuoze/Desktop/Django/pmw-dashboard/venv/Lib/site-packages/django_crontab/crontab.py'
# CRONTAB_DJANGO_PROJECT_NAME='core'
# CRONTAB_DJANGO_MANAGE_PATH='C:/Users/Ahmedrufai.Otuoze/Desktop/Django/pmw-dashboard/manage.py'
# CRONTAB_PYTHON_EXECUTABLE='C:/Users/Ahmedrufai.Otuoze/Anaconda/pythonw.exe'
# CRONTAB_DJANGO_SETTINGS_MODULE='C:/Users/Ahmedrufai.Otuoze/Desktop/Django/pmw-dashboard/core/settings.py'


# CRONJOBS = [
#     ('48, 49, 50 * * * *', 'core.cron.my_cron_job', '>> logs/file.log'),
# ]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.oracle',
#         'NAME': 'pacer7',
#         'USER': 'reports',
#         'PASSWORD': 'reports',        
#         'HOST': '',
#         'PORT': ''
#     }
# }

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}




# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",},
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = 'Africa/Lagos'

USE_I18N = True


# USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [
    BASE_DIR / "static"
]

# Base url to serve media files  
MEDIA_URL = "media/" 
# # Path where media is stored 
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


USE_L10N = False

DATETIME_INPUT_FORMATS = ['%Y-%m-%d %H:%M:%S',]